language: java
jdk: oraclejdk8
os: linux
cache:
  directories:
    - $HOME/.gradle
script: 
  - pwd
  - ls -l build
  - ls -l train-reference-data/build
addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - train-reference-data/build/libs/*.jar

