language: java
jdk: oraclejdk8
os: linux
cache:
  directories:
    - $HOME/.gradle
addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - train-reference-data/build/libs/train-reference-data-1.0-SNAPSHOT.jar
   key
