language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.gradle
script:
  - ./gradlew clean build
addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - train-reference-data/build/libs/*.jar

