# Warning: Remember to change use to centos for Centos7 image
# or centos for AWS image
version: 0.0
os: linux
files:
  - source: docker-compose.yml
    destination: /var/trainwatch
permissions:
  - object: /var
    pattern: "trainwatch"
    owner: centos
    group: centos
    mode: 555
    type:
      - directory
  - object: /var/trainwatch
    pattern: "**"
    owner: centos
    group: centos
    mode: 755
hooks:
  AfterInstall:
    - location: aws/hook-after-install.sh
  ApplicationStart:
    - location: aws/hook-application-start.sh
