# Warning: Remember to change use to centos for Centos7 image
# or centos for AWS image
version: 0.0
os: linux
files:
  - source: train-reference-data/build/libs/train-reference-data-1.0-SNAPSHOT.jar
    destination: /var/trainwatch/libs/
  - source: docker-compose.yml
    destination: /var/trainwatch/
permissions:
  - object: /var
    pattern: "trainwatch"
    owner: centos
    group: centos
    mode: 555
    type:
      - directory
  - object: /var/trainwatch
    pattern: "**"
    owner: centos
    group: centos
    mode: 555
hooks:
  BeforeInstall:
    - location: aws/hook-before-install.sh
  ApplicationStop:
    - location: aws/hook-application-stop.sh
