# Warning: Remember to change user to centos for Centos7 image
# or ec2-user for AWS image
version: 0.0
os: linux
files:
  - source: tools/
    destination: /var/trainwatch/tools/   
  - source: libs/tw-train-movement-1.0-SNAPSHOT.jar
    destination: /var/trainwatch/libs
  - source: libs/tw-search-api-1.0-SNAPSHOT.jar
    destination: /var/trainwatch/libs
  - source: aws/hazelcast/start.sh
    destination: /opt/hazelcast/bin
  - source: aws/hazelcast/hazelcast.xml
    destination: /opt/hazelcast/bin
  - source: creds.txt
    destination: /var/trainwatch
  - source: aws/kafka/server.properties
    destination: /opt/kafka/config
  - source: aws/kafka/kafka-server-stop.sh
    destination: /opt/kafka/bin
  - source: aws/kafka/zookeeper-server-stop.sh
    destination: /opt/kafka/bin
permissions:
  - object: /var
    pattern: "trainwatch"
    owner: centos
    group: centos
    mode: 755
    type:
      - directory
  - object: /var/trainwatch
    pattern: "**"
    owner: centos
    group: centos
    mode: 700
  - object: /opt/hazelcast/bin/hazelcast.xml
    owner: centos
    group: centos
    mode: 755
  - object: /opt/hazelcast/bin/start.sh
    owner: centos
    group: centos
    mode: 755
  - object: /opt/kafka/config/server.properties
    owner: centos
    group: centos
    mode: 755
  - object: /opt/kafka/bin/kafka-server-stop.sh
    owner: centos
    group: centos
    mode: 755
  - object: /opt/kafka/bin/zookeeper-server-stop.sh
    owner: centos
    group: centos
    mode: 755
hooks:
  ApplicationStop:
    - location: aws/hook-application-stop.sh
      timeout: 30
      runas: centos
  BeforeInstall:
    - location: aws/hook-before-install.sh
      timeout: 30
      runas: centos    
  ApplicationStart:
    - location: aws/hook-application-start.sh
      timeout: 30
      runas: centos
