#cloud-config
yum_repos:
  dockerrepo:
    name: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: true
    gpgcheck: true
    gpgkey: https://yum.dockerproject.org/gpg
repo_update: true
repo_upgrade: none
packages:
  - python
  - ruby
  - java-1.8.0-openjdk-devel
  - docker-engine
runcmd:
  - '/usr/bin/ln -f -s /usr/share/zoneinfo/GB /etc/localtime'
  - '/usr/bin/systemctl start docker'
  - '/usr/sbin/usermod -aG docker centos'
  - '/bin/curl -L -k https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose'
  - '/usr/bin/chmod +x /usr/local/bin/docker-compose'
  - '/usr/bin/curl -L -k https://aws-codedeploy-eu-west-1.s3.amazonaws.com/latest/install > /tmp/install'
  - '/usr/bin/chmod +x /tmp/install'
  - '/tmp/install auto'
  - '/bin/curl -L -o /tmp/hazelcast.tgz "http://download.hazelcast.com/download.jsp?version=hazelcast-3.6.2&type=tar&p=177120386177120386"'
  - '/bin/tar -xz -C /opt -f /tmp/hazelcast.tgz'
  - '/bin/chown -R centos:centos /opt/hazelcast-3.6.2'
  - '/bin/ln -s /opt/hazelcast-3.6.2 /opt/hazelcast'
  - '/bin/curl -L -o /tmp/kafka.tgz http://mirrors.ukfast.co.uk/sites/ftp.apache.org/kafka/0.9.0.1/kafka_2.11-0.9.0.1.tgz'
  - '/bin/tar -xz -C /opt -f /tmp/kafka.tgz'
  - '/bin/chown -R centos:centos /opt/kafka_2.11-0.9.0.1'
  - '/bin/ln -s /opt/kafka_2.11-0.9.0.1 /opt/kafka'
 
