#cloud-config
yum_repos:
  dockerrepo:
    name: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: true
    gpgcheck: true
    gpgkey: https://yum.dockerproject.org/gpg
repo_update: true
repo_upgrade: security
packages:
  - unzip
  - curl
  - wget
  - python
  - ruby
  - java-1.8.0-openjdk-devel
  - docker-engine
runcmd:
  - systemctl start docker
  - [ sh, -c, "usermod -a -G docker centos" ]
  - '/usr/bin/wget -O /tmp/install https://aws-codedeploy-eu-west-1.s3.amazonaws.com/latest/install'
  - '/usr/bin/chmod +x /tmp/install'
  - '/tmp/install auto'
